### ISSUE TITLE
idea for better system NOTICE

### ISSUE THREAD

**Issue by AmoAlireza** [GFWFuckers/MarzGosha#19]
thanks to @erfjab ❤
with this (https://github.com/GFWFuckers/MarzGosha/pull/17) PR i have a idea for NOTICE when user is disabled or limited and i make it possible.

this will check the user status is active or on hold if not on these status steps this will use CUSTOM_NOTICE_CONFIGS .env.

ps: it support format variables, like you can use {USERNAME},{SERVER_IP},{DATA_LEFT}, and other variables.
`vless://0@{SERVER_IP}:1?encryption=none&security=none&type=tcp&headerType=none#%7BUSERNAME%7D`

sorry to not open PR for this 😅

.env.example:
```python
# Custom NOTICE inbound in sub link
CUSTOM_NOTICE_CONFIGS = vless://... 
```

app/subscription/share.py:
```python
from config import (ACTIVE_STATUS_TEXT, DISABLED_STATUS_TEXT,
                    EXPIRED_STATUS_TEXT, LIMITED_STATUS_TEXT,
                    ONHOLD_STATUS_TEXT, RANDOMIZE_SUBSCRIPTION_CONFIGS,
                    CUSTOM_NOTICE_CONFIGS)
```
```python
def generate_subscription(
    user: "UserResponse",
    config_format: Literal["v2ray", "clash-meta", "clash", "sing-box", "outline", "v2ray-json"],
    as_base64: bool,
) -> str:
    kwargs = {
        "proxies": user.proxies,
        "inbounds": user.inbounds,
        "extra_data": user.__dict__,
    }

    format_variables = setup_format_variables(user.__dict__)

    if user.status not in ['active', 'on_hold']:
        if CUSTOM_NOTICE_CONFIGS and config_format == "v2ray":
            config = "\n".join(CUSTOM_NOTICE_CONFIGS)
            config = config.format_map(format_variables)
        else:
            config = ""
    else:
        if config_format == "v2ray":
            config = "\n".join(generate_v2ray_links(**kwargs))
        elif config_format == "clash-meta":
            config = generate_clash_subscription(**kwargs, is_meta=True)
        elif config_format == "clash":
            config = generate_clash_subscription(**kwargs)
        elif config_format == "sing-box":
            config = generate_singbox_subscription(**kwargs)
        elif config_format == "outline":
            config = generate_outline_subscription(**kwargs)
        elif config_format == "v2ray-json":
            config = generate_v2ray_json_subscription(**kwargs)
        else:
            raise ValueError(f'Unsupported format "{config_format}"')

    if RANDOMIZE_SUBSCRIPTION_CONFIGS is not False:
        config = randomize_sub_config(config, config_format)

    if as_base64:
        config = base64.b64encode(config.encode()).decode()

    return config
```

config.py:
```python
from urllib.parse import unquote

CUSTOM_NOTICE_CONFIGS = config(
    'CUSTOM_NOTICE_CONFIGS',
    default=None,
    cast=lambda v: [unquote(s.strip()) for s in v.split(' , ') if s.strip()]
)
```

**Comment by erfjab** [comment]
Hello my dear friend, Thank you for your attention. How is this different from the simple model? I think only their texts are different. Right?

**Comment by erfjab** [comment]
If you have any other ideas and want us to talk about it. You can find me at telegram with @erfjab id.

**Comment by AmoAlireza** [comment]
> Hello my dear friend, Thank you for your attention. How is this different from the simple model? I think only their texts are different. Right?

hello, yeah i change texts and added setup_format_variables to support the format variables and change the active+on_hold `if` placement to not include other configs in sub link.

**Comment by erfjab** [comment]
> hello, yeah i change texts and added setup_format_variables to support the format variables and change the active+on_hold if placement to not include other configs in sub link.

For on_hold users, we should not add. Because when they use it, He stays on_hold. This becomes a problem.

**Comment by AmoAlireza** [comment]
> > hello, yeah i change texts and added setup_format_variables to support the format variables and change the active+on_hold if placement to not include other configs in sub link.
> 
> For on_hold users, we should not add. Because when they use it, He stays on_hold. This becomes a problem.

yeah i didn't add it => ``` if user.status not in ['active', 'on_hold']:```

i use not in 😅

**Comment by erfjab** [comment]
This method is a problem that only works for v2ray. How do you want to fix?

**Comment by erfjab** [comment]
This method is a problem that only works for v2ray. How do you want to fix?

**Comment by AmoAlireza** [comment]
> This method is a problem that only works for v2ray. How do you want to fix?

yeah that's one of the reasons i don't send the PR, for now it's just a idea and i will try to make it better.

**Comment by AmoAlireza** [comment]
i just update the generate_subscription to fix only work for v2ray and improve performance.

app/subscription/share.py:
```python
def generate_subscription(
    user: "UserResponse",
    config_format: Literal["v2ray", "clash-meta", "clash", "sing-box", "outline", "v2ray-json"],
    as_base64: bool,
) -> str:
    kwargs = {
        "proxies": user.proxies,
        "inbounds": user.inbounds,
        "extra_data": user.__dict__,
    }

    if user.status not in ['active', 'on_hold']:
        if CUSTOM_NOTICE_CONFIGS:
            format_variables = setup_format_variables(user.__dict__)
            config = "\n".join(notice.format_map(format_variables)
                               for notice in CUSTOM_NOTICE_CONFIGS)
        else:
            config = ""
    else:
        if config_format == "v2ray":
            config = "\n".join(generate_v2ray_links(**kwargs))
        elif config_format == "clash-meta":
            config = generate_clash_subscription(**kwargs, is_meta=True)
        elif config_format == "clash":
            config = generate_clash_subscription(**kwargs)
        elif config_format == "sing-box":
            config = generate_singbox_subscription(**kwargs)
        elif config_format == "outline":
            config = generate_outline_subscription(**kwargs)
        elif config_format == "v2ray-json":
            config = generate_v2ray_json_subscription(**kwargs)
        else:
            raise ValueError(f'Unsupported format "{config_format}"')

    if RANDOMIZE_SUBSCRIPTION_CONFIGS is not False:
        config = randomize_sub_config(config, config_format)

    if as_base64:
        config = base64.b64encode(config.encode()).decode()

    return config
```
